### ISSUE TITLE
Which is more Better? quartzite or this

### ISSUE THREAD

**Issue by MokkeMeguru** [duct-framework/scheduler.simple#3]
Hello!
I want to build a duct web application
this application does

- every an hour, this application sends clients a message by  [webpush](https://github.com/web-push-libs/webpush-java)

So I want to use any scheduler library such as this.
But 
- considering extensibility, I think we should use [quartzite](https://github.com/michaelklishin/quartzite), 
- considering compatibility with duct, we should use this library.

Can you give me any advice?

**Comment by weavejester** [comment]
You can always start with simple.scheduler and switch later. Other than that, you'll have to use your own judgement to decide.

**Comment by MokkeMeguru** [comment]
OK, I'll try this at first.
